feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      reportingApiClient:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
        requestInterceptors:
          - com.feignstudy.demo.interceptors.ReportingApiInterceptor


reporting-api-client:
  host: https://sandbox-reporting.rpdpymnt.com
  token-expiration-time: 10 # in minutes
  merchant-login: demo@financialhouse.io
  merchant-password: cjaiU8CV


spring:
  datasource:
    url: 'jdbc:h2:file:/data/demo'
    username: sa
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.H2Dialect'
