teste:
  abc:
    first-list:
      - bananinha
      - joao_das_couves
      - my_lord
    second-list:
      - bananinha
      - joao_das_couves
      - my_lord
    third-list:
      - bananinha
      - joao_das_couves
      - my_lord
    fourth-list:
      - 0.75
      - 1.50
      - 2.00
    fifth-list:
      - -5000
      - -5008
      - -5010