teste:
  abc:
    first-list:
      - bananinha
      - joao_das_couves
      - my_lord
    second-list:
      - bananinha
      - joao_das_couves
      - my_lord
    third-list:
      - bananinha
      - joao_das_couves
      - my_lord
